list:
  - 黄焖鸡
  - 炸酱面
  - 鸡公煲
  - 西红柿鸡蛋盖饭
  - 麻婆豆腐盖饭
  - 口水鸡
  - 酱牛肉
  - 麦当劳
  - 蒸卤面
  - 蛋炒饭
  - 猪脚饭
  - 回锅肉
  - 日式咖喱饭
  - 韩式炸鸡
  - 北京烤鸭
  - 凉皮+肉夹馍
  - 炸串
  - 烤冷面
  - 手抓饼
  - 水饺
  - 中式炸鸡
  - 烧烤
  - 农家小炒肉盖饭
  - 蔬菜沙拉
  - 黑椒牛柳盖饭
  - 螺蛳粉
  - 武汉热干面
  - 华莱士（小心喷射）
  - 麻辣香锅
  - 红烧肉
  - 火锅
  - 香煎鸡胸健康餐
  - 披萨
  - 麻辣烫
  - 泡面（不要酸菜）
