list:
  - 黄焖鸡
  - 炸酱面
  - 鸡公煲
  - 西红柿鸡蛋盖饭
  - 麻婆豆腐盖饭
  - 口水鸡
  - 酱牛肉
  - 麦当劳
  - 蒸卤面
  - 蛋炒饭
  - 猪脚饭
  - 回锅肉
  - 日式咖喱饭
  - 韩式炸鸡
  - 北京烤鸭
  - 凉皮+肉夹馍
  - 炸串
  - 烤冷面
  - 手抓饼
  - 水饺
  - 中式炸鸡
  - 烧烤
  - 农家小炒肉盖饭
  - 蔬菜沙拉
  - 黑椒牛柳盖饭
  - 螺蛳粉
  - 武汉热干面
  - 华莱士（小心喷射）
  - 麻辣香锅
  - 红烧肉
  - 火锅
  - 香煎鸡胸健康餐
  - 披萨
  - 麻辣烫
  - 泡面（不要酸菜）
  - 菠菜炒鸡蛋
  - 炒滑蛋
  - 炒茄子
  - 炒青菜
  - 葱煎豆腐
  - 地三鲜
  - 干锅花菜
  - 蚝油三鲜菇
  - 蚝油生菜
  - 红烧冬瓜
  - 红烧茄子
  - 虎皮青椒
  - 冷吃兔
  - 荔枝肉
  - 凉拌鸡丝
  - 萝卜炖羊排
  - 麻辣香锅
  - 梅菜扣肉
  - 啤酒鸭
  - 水煮牛肉
  - 水煮肉片
  - 蒜苔炒肉末
  - 糖醋里脊
  - 糖醋排骨
  - 土豆炖排骨
  - 无骨鸡爪
  - 西红柿牛腩
