list:
  - receive:
      text: # text可以是string或string[]
        - 涩涩
        - 色色
        - 瑟瑟
      is_contains: true # true为包含模式：只要含有关键词就会触发
    return:
      text: 变态，禁止涩涩！

  - receive:
      text: 我好了
      is_contains: false
    return:
      text: 憋回去，不许好喵

  - receive:
      text:
        - 爽不爽
        - 爽吗
      is_contains: true
    return:
      text: 啧，就这？

  - receive:
      text:
        - 芜湖起飞
        - 芜湖
      is_contains: false
    return:
      text: 芜湖起飞

  - receive:
      text:
        - 开冲
        - 冲
        - 冲！
      is_contains: false
    return:
      image: chong.jpg

  - receive:
      text: 好涩哦
      is_contains: false
    return:
      image: lianhon.jpg

  - receive:
      text: 
        - 开摆
        - 摆了
      is_contains: true
    return:
      image: linghuofendou.jpg # 图片名，会映射到/assets/images/{图片名}

  - receive:
      text:
        - 早安
        - 早上好
      is_contains: true
    return:
      image: zao.jpg

  - receive:
      text:
        - 早
      is_contains: false
    return:
      image: zao.jpg

  - receive:
      text: 呜呜呜
      is_contains: true
    return: 
      text: 摸摸不哭

  - receive:
      text: 乐
      is_contains: false
    return: 
      image: le.jpg

